### PR TITLE
feat: add config option to explicitly set the buildcache tag to use

### PR DESCRIPTION
**Pull request by xTVaser**
Quick new config option for the action so users can explicitly set the buildcache tag to use.

Recently (this week) buildcache changed their latest release to be built on Ubuntu 22.04 https://github.com/mbitsnbites/buildcache/commit/1da5892ee5c6375921613f13206a360a54e66423

This means that we now run into glibc version errors on older (but still LTS) Ubuntu 20.04 runners.  For example - https://github.com/open-goal/jak-project/actions/runs/3286511063/jobs/5414699484

So this change lets us rollback to the previous tag which still supported 20.04

Changes in action:
- https://github.com/open-goal/jak-project/actions/runs/3286668410/jobs/5415017907
  - The GCC build lacks the flag, so pulls the latest and fails
  - The Clang build specifies `v0.27.6`
  
Not sure if i rebuilt the `./dist` folder correctly or not (big diff)

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
Looks good - this is where it would be much cooler if my CI hadn't suffered some sort of entropic bitrot as CI would just let us know the dist stuff was rebuilt correctly ;-)
Let me try to verify, then can release

**Comment by mikehardy** [comment]
Irony, the CI fails for the reason you are trying to fix https://github.com/mikehardy/buildcache-action/actions/runs/3286738940/jobs/5425883555

I wonder if you could reach in to the workflows and actually alter that one to use the new flag? That would serve as a great test

**Comment by xTVaser** [comment]
kk, should work now -- was able to get all tests passing (except the react-native-build but that seems to be failing on master as well) https://github.com/xTVaser/buildcache-action/pull/1

**Review by mikehardy — APPROVED** [review]
Looks really good! Nice work on the CI actions
Yes the react-native one is busted at the moment, odd error - haven't had time to look, but not the fault of this PR, this PR is a step forward in many ways now. Thanks!

**Comment by mikehardy** [comment]
released as v2.1.0, with the v2 tag "slid" up to match (since that's way to do semver in github workflow actions, near as I can tell: https://github.com/mikehardy/buildcache-action/releases - thanks again

**Pull request merged**
