### PR TITLE
Fix path issues

### PR DESCRIPTION
**Pull request by orgads**
Mostly on Windows, but also on other platforms, when `BUILDCACHE_DIR` env variable is used.

### CODE REVIEW

**Comment by orgads** [comment]
This branch is based on no-impersonate (it's hard to use separate branches when the dist directory is part of the repo :/)

**Review by mikehardy — APPROVED** [review]
I'm okay with chained-together commits, the dist thing is an artifact of me using the ccache action as a base, they do that and I think it's required if you want to use typescript as the github actions runner needs it pre-transpiled + bundled. Anyway, no worries - your commits are very well organized so reviewing this is a pleasure.

This all seems fine to me, I just kicked off the CI runs

**Comment by mikehardy** [comment]
I'm going to close the original PR on impersonation as I don't think it's reasonable to untangle them, and it can ride in on this PR. If I'm mistaken in some way, can always reopen it

**Comment by mikehardy** [comment]
Some linting issues at minimum, react-native run still going

**Comment by orgads** [comment]
2 minutes, I'll fix the prettier issues.

**Comment by mikehardy** [comment]
These are actually more serious - I'm not sure exactly how to fail the react-native compile test based on this type of failure (I did not spend much time investigating though, TBH - I just visually inspect), but there's a problem here

https://github.com/mikehardy/buildcache-action/pull/34/checks?check_run_id=3125987994#step:27:20

```

Warning: buildcache: unable to upload buildlog: Error: File ../custom_buildcache.log does not exist
Warning: buildcache: unable to delete buildcache.log Error: ENOENT: no such file or directory, unlink '../custom_buildcache.log'
buildcache: saving cache with key "buildcache-react-native-compile-2021-07-21T16:28:25.384Z".
Warning: buildcache: caching not working: AssertionError [ERR_ASSERTION]: Invalid pattern '../custom_buildcache_dir'. Relative pathing '.' and '..' is not allowed.

```

**Comment by mikehardy** [comment]
Dang. The error I noted has been happening quite some time, it is unrelated and not a regression on this PR.

**Comment by orgads** [comment]
I suppose the intent was to use a directory relative to github workspace. This can be done by detecting that the path is relative, and the using `path.resolve` with the workspace as base.

**Comment by mikehardy** [comment]
If this build passes (with the error that is not a regression) I'll merge as is, it's solid incremental progress regardless I think.
If you want to fix that too I would obviously be thrilled but is not gating this

**Comment by orgads** [comment]
I'll try. :)

**Comment by mikehardy** [comment]
This is merged now so it's a clean base on main branch again at least

**Comment by orgads** [comment]
Thank you.

**Pull request merged**
